FROM golang:1.19-alpine

WORKDIR /github.com/cryptag/leapchat/miniware

WORKDIR /github.com/cryptag/leapchat

COPY miniware/* miniware/
COPY *.go .
COPY go.* .
COPY LICENSE.md .

RUN go build -o /leapchat

EXPOSE 8080

CMD ["/leapchat"]